### ISSUE TITLE
migrate.py misses migration of some test files

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#460] opened 2020-02-26 18:01 UTC
All files for the `script_inventory_ec2` integration test should be migrated:

https://github.com/ansible-community/collection_migration/blob/b00aab6d3b1021e201b16b6be1acf24b906de57c/scenarios/nwo/community.yml#L4-L8

However,  the `__init__.py` files remain even after migration:

https://github.com/ansible-collection-migration/ansible-base/blob/devel/test/integration/targets/script_inventory_ec2/lib/boto/ec2/__init__.py

**Comment by bcoca** [comment] 2020-02-26 18:20
confirmed, only the __init__.py files are ignored and not trasnfered (since most are non 0 bytes, they are kept in core)

**Comment by bcoca** [comment] 2020-02-26 18:56
mostly fixed via b00aab6d3b1021e201b16b6be1acf24b906de57c , still leaving copies in core, but at least collection will be correct (will fix core in subsequent update)

**Closed by bcoca** 2020-02-26 18:56 UTC
