### ISSUE TITLE
ansible-minimal: Contains deprecated modules

### ISSUE THREAD

**Issue by gundalow** [ansible-community/collection_migration#194] opened 2019-12-12 20:09 UTC
This may get fixed by https://github.com/ansible-community/collection_migration/pull/192

This was found when @samccann was testing `make webdocs` from ansible-minimal

ansible-minimal currently contains lots of deprecated modules, a random selection being:

```
./network/junos/_junos_static_route.py
./network/f5/_bigip_asm_policy.py
./network/f5/_bigip_gtm_facts.py
./network/f5/_bigip_facts.py
./network/layer3/_net_vrf.py
./network/layer3/_net_l3_interface.py
./network/system/_net_logging.py
./network/system/_net_banner.py
./network/system/_net_user.py
./network/system/_net_system.py
./network/eos/_eos_l2_interface.py
./network/eos/_eos_linkagg.py
./network/eos/_eos_vlan.py
./network/eos/_eos_l3_interface.py
./network/eos/_eos_interface.py
./network/ios/_ios_l3_interface.py
./network/ios/_ios_interface.py
./network/ios/_ios_vlan.py
./network/ios/_ios_l2_interface.py
./network/cloudengine/ce_is_is_instance.py
./network/cloudengine/ce_is_is_view.py
./network/cloudengine/ce_is_is_interface.py
./network/cloudengine/ce_mdn_interface.py
./network/cloudengine/ce_multicast_igmp_enable.py
./network/cloudengine/ce_multicast_global.py
./network/aos/_aos_device.py
./network/aos/_aos_blueprint_virtnet.py
./network/aos/_aos_blueprint_param.py
./network/aos/_aos_rack_type.py
./network/aos/_aos_asn_pool.py
./network/aos/_aos_ip_pool.py
./network/aos/_aos_external_router.py
./network/aos/_aos_logical_device_map.py
./network/aos/_aos_blueprint.py
./network/aos/_aos_login.py
./network/aos/_aos_template.py
./network/aos/_aos_logical_device.py
./network/netvisor/_pn_trunk.py
./network/netvisor/_pn_vlag.py
./network/netvisor/_pn_vrouter.py
./network/netvisor/_pn_vrouterif.py
./network/netvisor/_pn_show.py
./network/netvisor/_pn_vrouterlbif.py
./network/netvisor/_pn_ospfarea.py
./network/netvisor/_pn_cluster.py
./network/netvisor/_pn_ospf.py
./network/netvisor/_pn_vlan.py
./network/netvisor/_pn_vrouterbgp.py
./network/protocol/_net_lldp.py
```

**Comment by bcoca** [comment] 2019-12-17 19:52
closing as dupe of #187

**Closed** 2019-12-17 20:09 UTC
Labels: bug
