### ISSUE TITLE
Missing integration test files in migrated collection

### ISSUE THREAD

**Issue by jillr** [ansible-community/collection_migration#292] opened 2020-02-05 16:52 UTC
community.amazon from #246 results in missing files from several integration tests.
Identified so far:
`ec2_eip` ends up with an entirely empty task dir
`ec2_instance` is missing `tasks/find_ami.yml`
`ec2_vpc_net` and `rds_subnet_group` missing contents of defaults dir
Example:
```
jill@bionic:~/collections/ansible_collections/community/amazon$ ll tests/integration/targets/ec2_vpc_net/defaults/
total 0
drwxrwxr-x 2 jill jill  6 Feb  5 00:01 ./
drwxrwxr-x 5 jill jill 62 Feb  5 00:01 ../

```
vs devel:
```
jill@zim:~/local/ansible/ansible$ ll test/integration/targets/ec2_vpc_net/defaults/
total 12
-rw-rw-r-- 1 jill jill 229 Jan 15 18:10 main.yml
```

Still working through a list of other failing tests.

**Comment by jillr** [comment] 2020-02-05 17:02
Specific migrate command being used: `python3 -m migrate -m -s scenarios/nwo/ --skip-publish --convert-symlinks`

**Comment by mkrizek** [comment] 2020-02-05 18:45
@jillr Thanks, this revealed the following issues in the migration script:
https://github.com/ansible-community/collection_migration/issues/297
https://github.com/ansible-community/collection_migration/issues/299

**Comment by mkrizek** [comment] 2020-02-06 14:31
The root cause of this should be fixed in https://github.com/ansible-community/collection_migration/pull/306. I am going to go ahead and close this. Feel free to re-open/open a new issue if needed. Thanks!

**Closed by mkrizek** 2020-02-06 14:31 UTC
