### ISSUE TITLE
migrate.py removes in use conftest.py from ansible-base

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#328] opened 2020-02-08 03:59 UTC
The migration script removes `test/units/module_utils/conftest.py` from ansible-base even though it is used by unit tests that remain in ansible-base.

**Comment by webknjaz** [comment] 2020-02-11 13:02
I hope to resolve this w/ https://github.com/ansible/ansible/pull/66430

**Comment by bcoca** [comment] 2020-02-19 21:05
closing as dupe of #191

**Closed by bcoca** 2020-02-19 21:05 UTC
Labels: blocker, bug
